# Generated by Django 5.1.7 on 2025-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipapp', '0002_sponsorshipmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='universities/')),
                ('website_url', models.URLField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('established_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(help_text='Please upload your photo', upload_to='testimonials/'),
        ),
    ]
