# Generated by Django 5.1.7 on 2025-05-18 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipapp', '0003_university_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['ranking', 'name'], 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='scholarshipapp.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='university',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=9999, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(help_text='Upload your photo (recommended size: 400x400px)', upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(help_text='Upload university image (recommended size: 800x600px)', upload_to='universities/'),
        ),
    ]
